Repository mpuskadij/ServiceSync, pull requests merged in 2024-12, with the labels that each got.

#6 FTR-15: Reviews
  app/src/main/java/hr/foi/air/servicesync/backend/FirestoreReviews.kt
  app/src/main/java/hr/foi/air/servicesync/business/ReviewHandler.kt
  app/src/main/java/hr/foi/air/servicesync/data/Review.kt
  app/src/main/java/hr/foi/air/servicesync/navigation/AppNavHost.kt
  app/src/main/java/hr/foi/air/servicesync/ui/components/ReviewCard.kt
  app/src/main/java/hr/foi/air/servicesync/ui/components/ReviewList.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/CompanyDetailsContent.kt
  app/src/main/java/hr/foi/air/servicesync/ui/screens/AddReviewScreen.kt
  app/src/main/java/hr/foi/air/servicesync/ui/screens/MainScreen.kt
  app/src/main/java/hr/foi/air/servicesync/ui/screens/SearchScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, design

#10 FTR-83 fetch available appointments based on the working hours
  app/src/main/java/hr/foi/air/servicesync/backend/FirestoreCompanyDetails.kt
  app/src/main/java/hr/foi/air/servicesync/backend/FirestoreService.kt
  app/src/main/java/hr/foi/air/servicesync/business/ReservationManager.kt
  app/src/main/java/hr/foi/air/servicesync/ui/screens/ServiceReservationScreen.kt
Labels: enhancement

#13 Develop
  app/build.gradle.kts
  app/src/main/java/hr/foi/air/servicesync/MainActivity.kt
  app/src/main/java/hr/foi/air/servicesync/abstracted/CompanyDetails.kt
  app/src/main/java/hr/foi/air/servicesync/business/CompanyDetailsHandler.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/CompanyDetailsContent.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/dujino.txt
  maps/src/main/java/com/example/maps/interfaces/IMapProvider.kt
Labels: enhancement

#14 FTR-84 registration flow is weird
  app/src/main/java/hr/foi/air/servicesync/backend/FirestoreUserDetails.kt
  app/src/main/java/hr/foi/air/servicesync/business/UserDataHandler.kt
  app/src/main/java/hr/foi/air/servicesync/business/loginRegisterHandler.kt
  app/src/main/java/hr/foi/air/servicesync/ui/screens/RegistrationScreen.kt
Labels: bug fix

#16 FTR-13: Multi - Language Support
  app/build.gradle.kts
  app/src/main/java/hr/foi/air/servicesync/MainActivity.kt
  app/src/main/java/hr/foi/air/servicesync/business/LanguageChangeHelper.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/ProfileContent.kt
  app/src/main/java/hr/foi/air/servicesync/ui/items/LocalesFlags.kt
  app/src/main/java/hr/foi/air/servicesync/ui/screens/ProfileScreen.kt
  app/src/main/res/resources.properties
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, design

#17 FTR-87 fix shrink padding for category filters
  app/src/main/java/hr/foi/air/servicesync/ui/contents/ProfileContent.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/SearchContent.kt
  app/src/main/java/hr/foi/air/servicesync/ui/screens/SearchScreen.kt
Labels: bug fix
