Repository mpuskadij/ServiceSync, pull requests merged in 2025-01, with the labels that each got.

#18 FTR-88: Implement-a-server-for-notifications
  app/src/main/java/hr/foi/air/servicesync/backend/FirestoreService.kt
Labels: enhancement

#19 FTR-10 Future appointment calendar
  app/src/main/java/hr/foi/air/servicesync/backend/FirestoreService.kt
  app/src/main/java/hr/foi/air/servicesync/business/ReservationManager.kt
  app/src/main/java/hr/foi/air/servicesync/business/Utils.kt
  app/src/main/java/hr/foi/air/servicesync/navigation/AppNavHost.kt
  app/src/main/java/hr/foi/air/servicesync/ui/components/ReservationItem.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/CalendarContent.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/ProfileContent.kt
  app/src/main/java/hr/foi/air/servicesync/ui/screens/CalendarScreen.kt
  app/src/main/java/hr/foi/air/servicesync/ui/screens/CompanyDetailsWithHeader.kt
  app/src/main/java/hr/foi/air/servicesync/ui/screens/ProfileScreen.kt
  app/src/main/res/drawable/baseline_access_time_filled_24.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, bug fix

#21 FTR-89: Add sum of all reviews
  app/src/main/java/hr/foi/air/servicesync/business/ReviewHandler.kt
  app/src/main/java/hr/foi/air/servicesync/ui/components/CompanyCard.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/SearchContent.kt
  app/src/main/java/hr/foi/air/servicesync/ui/theme/Theme.kt
Labels: design, bug fix

#23 FTR-101 review related toasts are only in English, FTR-104 - loading indicator placment
  app/src/main/java/hr/foi/air/servicesync/navigation/AppNavHost.kt
  app/src/main/java/hr/foi/air/servicesync/ui/components/QRScanner.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/SearchContent.kt
  app/src/main/java/hr/foi/air/servicesync/ui/screens/AddReviewScreen.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug fix

#22 FTR-105: Working hours on company details is displaying a number instead of an interval
  app/src/main/java/hr/foi/air/servicesync/backend/FirestoreCompanyDetails.kt
  app/src/main/java/hr/foi/air/servicesync/business/CompanyDetailsHandler.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/CompanyDetailsContent.kt
Labels: bug fix

#25 FTR-100 Change profile picture
  app/build.gradle.kts
  app/src/main/java/hr/foi/air/servicesync/backend/FirestoreUserDetails.kt
  app/src/main/java/hr/foi/air/servicesync/backend/ImgurApi.kt
  app/src/main/java/hr/foi/air/servicesync/backend/RetrofitInstance.kt
  app/src/main/java/hr/foi/air/servicesync/business/ImageProcessor.kt
  app/src/main/java/hr/foi/air/servicesync/business/UserDataHandler.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/ProfileContent.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/ProfileImageChanger.kt
  app/src/main/res/drawable/baseline_add_photo_alternate_24.xml
  app/src/main/res/values/secrets.xml
Labels: enhancement, bug fix

#26 FTR - 86: Refactored SearchContent
  app/src/main/java/hr/foi/air/servicesync/backend/FirestoreCompanyService.kt
  app/src/main/java/hr/foi/air/servicesync/business/CategoryHandler.kt
  app/src/main/java/hr/foi/air/servicesync/business/CompanyDetailsHandler.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/CompanyDetailsContent.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/SearchContent.kt
Labels: documentation, enhancement

#27 FTR-91: Limit reviews
  app/build.gradle.kts
  app/src/main/java/hr/foi/air/servicesync/backend/FirestoreReviews.kt
  app/src/main/java/hr/foi/air/servicesync/backend/FirestoreService.kt
  app/src/main/java/hr/foi/air/servicesync/business/ReservationManager.kt
  app/src/main/java/hr/foi/air/servicesync/business/ReviewHandler.kt
  app/src/main/java/hr/foi/air/servicesync/ui/components/ReservationItemDone.kt
  app/src/main/java/hr/foi/air/servicesync/ui/components/ReviewCard.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/CalendarContent.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/CompanyDetailsContent.kt
  app/src/main/java/hr/foi/air/servicesync/ui/screens/AddReviewScreen.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, design, bug fix

#28 FTR-14 favorites
  app/src/main/java/hr/foi/air/servicesync/backend/FirestoreFavorites.kt
  app/src/main/java/hr/foi/air/servicesync/backend/FirestoreService.kt
  app/src/main/java/hr/foi/air/servicesync/business/CompanyDetailsHandler.kt
  app/src/main/java/hr/foi/air/servicesync/business/FavoritesHandler.kt
  app/src/main/java/hr/foi/air/servicesync/business/ReservationManager.kt
  app/src/main/java/hr/foi/air/servicesync/data/Favorite.kt
  app/src/main/java/hr/foi/air/servicesync/navigation/AppNavHost.kt
  app/src/main/java/hr/foi/air/servicesync/ui/components/BackButton.kt
  app/src/main/java/hr/foi/air/servicesync/ui/components/CompanyNameAndImage.kt
  app/src/main/java/hr/foi/air/servicesync/ui/components/ReservationItem.kt
  app/src/main/java/hr/foi/air/servicesync/ui/components/ReservationItemDone.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/CalendarContent.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/CompanyDetailsContent.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/FavoriteContent.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/SearchContent.kt
  app/src/main/java/hr/foi/air/servicesync/ui/items/NavItem.kt
  app/src/main/java/hr/foi/air/servicesync/ui/screens/FavoriteScreen.kt
  app/src/main/java/hr/foi/air/servicesync/ui/screens/MainScreen.kt
  app/src/main/java/hr/foi/air/servicesync/ui/screens/ServiceReservationScreen.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, design, bug fix

#30 FTR-117 add final touches to the UI
  app/src/main/java/hr/foi/air/servicesync/ui/components/CompanyCard.kt
  app/src/main/java/hr/foi/air/servicesync/ui/components/FloatingCard.kt
  app/src/main/java/hr/foi/air/servicesync/ui/components/ReservationItem.kt
  app/src/main/java/hr/foi/air/servicesync/ui/components/ReviewCard.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/CalendarContent.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/CompanyDetailsContent.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/FavoriteContent.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/ProfileContent.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/ProfileImageChanger.kt
  app/src/main/java/hr/foi/air/servicesync/ui/contents/SearchContent.kt
  app/src/main/java/hr/foi/air/servicesync/ui/screens/AddReviewScreen.kt
  app/src/main/java/hr/foi/air/servicesync/ui/screens/LoginScreen.kt
  app/src/main/java/hr/foi/air/servicesync/ui/screens/ProfileScreen.kt
  app/src/main/java/hr/foi/air/servicesync/ui/screens/ServiceReservationScreen.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values/secrets.xml
  app/src/main/res/values/strings.xml
Labels: design, bug fix
